name: SonarQube Analysis and Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          # Download SonarQube Scanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"

          # Run SonarQube Scanner
          sonar-scanner \
            -Dsonar.projectKey=DevSecOps-Pipeline \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

          # Capture the CE Task URL
          ceTaskUrl=$(grep -oP '(?<=ceTaskUrl=).*' ./.scannerwork/report-task.txt || echo "")
          echo "CE Task URL: $ceTaskUrl"
          echo "ceTaskUrl=$ceTaskUrl" >> $GITHUB_ENV

      - name: Wait for SonarQube Analysis and Send Email
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          CE_TASK_URL: ${{ env.ceTaskUrl }}
        run: |
          if [ -z "$CE_TASK_URL" ]; then
            echo "SonarQube analysis task URL not found. Exiting."
            exit 1
          fi

          # Poll the CE task until it's completed
          status="PENDING"
          while [ "$status" = "PENDING" ] || [ "$status" = "IN_PROGRESS" ]; do
            sleep 5
            response=$(curl -s -u $SONAR_TOKEN: "$CE_TASK_URL")
            status=$(echo "$response" | jq -r '.task.status')
            echo "Current status: $status"
          done
          if [ "$status" != "SUCCESS" ]; then
            echo "SonarQube analysis failed."
            exit 1
          fi
          analysisId=$(echo "$response" | jq -r '.task.analysisId')

          # Get SonarQube Analysis Report
          reportUrl="$SONAR_HOST_URL/api/qualitygates/project_status?analysisId=$analysisId"
          response=$(curl -s -u $SONAR_TOKEN: "$reportUrl")
          echo "$response" > sonarqube_report.json
          status=$(echo "$response" | jq -r '.projectStatus.status')

          # Send Email with SonarQube Report
          echo "Quality Gate Status: $status"
          sendmail -s "SonarQube Analysis Report - $status" \
                   -u "$EMAIL_USERNAME" \
                   -p "$EMAIL_PASSWORD" \
                   -t "recipient@example.com" \
                   -f "$EMAIL_USERNAME" \
                   -b "SonarQube Analysis Report:<br>Quality Gate Status: $status<br>Detailed report attached." \
                   -a sonarqube_report.json

      - name: Build Docker image
        run: |
          docker build -t rajashekar1/my-f1hub:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push rajashekar1/my-f1hub:${{ github.sha }}
