name: DecSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis and Email Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"
          sonar-scanner \
            -Dsonar.projectKey=DevSecOps-Pipeline \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Wait for SonarQube Analysis to Complete
        id: ceTask
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ceTaskUrl=$(grep -oP '(?<=ceTaskUrl=).*' ./.scannerwork/report-task.txt)
          echo "CE Task URL: $ceTaskUrl"
          status="PENDING"
          while [ "$status" = "PENDING" ] || [ "$status" = "IN_PROGRESS" ]; do
            sleep 5
            response=$(curl -s -u $SONAR_TOKEN: "$ceTaskUrl")
            status=$(echo "$response" | jq -r '.task.status')
            echo "Current status: $status"
          done
          if [ "$status" != "SUCCESS" ]; then
            echo "SonarQube analysis failed."
            exit 1
          fi
          analysisId=$(echo "$response" | jq -r '.task.analysisId')
          echo "analysisId=$analysisId" >> $GITHUB_OUTPUT

      - name: Get SonarQube Analysis Report
        id: getReport
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          analysisId=${{ steps.ceTask.outputs.analysisId }}
          reportUrl="$SONAR_HOST_URL/api/qualitygates/project_status?analysisId=$analysisId"
          response=$(curl -s -u $SONAR_TOKEN: "$reportUrl")
          echo "$response" > sonarqube_report.json
          status=$(echo "$response" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $status"
          echo "status=$status" >> $GITHUB_OUTPUT

      - name: Send Email with SonarQube Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Analysis Report - ${{ steps.getReport.outputs.status }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          secure: true
          html_body: |
            <h1>SonarQube Analysis Report</h1>
            <p><strong>Quality Gate Status:</strong> ${{ steps.getReport.outputs.status }}</p>
            <p>Detailed report is attached.</p>
          attachments: sonarqube_report.json

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t rajashekar1/my-f1hub:${{ github.sha }} .

  trivy:
    name: Trivy Scan Docker Image
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Docker image with Trivy
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL rajashekar1/my-f1hub:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push rajashekar1/my-f1hub:${{ github.sha }}
